# Generated by Django 5.1.2 on 2024-10-28 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Museo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del museo')),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_fundacion', models.DateField(help_text='Fecha en que se fundo el museo', null=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('idiomas', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('museo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmuseo.museo')),
            ],
        ),
        migrations.CreateModel(
            name='Exposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad', models.IntegerField(default=60)),
                ('museo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmuseo.museo')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la obra')),
                ('autor', models.CharField(blank=True, max_length=100)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('pintura', 'Pintura'), ('escultura', 'Escultura')], default='pintura', max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='obras/')),
                ('exposicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmuseo.exposicion')),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('biografia', models.TextField()),
                ('nacionalidad', models.CharField(blank=True, choices=[('espanola', 'Española'), ('italiana', 'Italiana')], max_length=50)),
                ('obras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmuseo.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida', models.IntegerField(default=0)),
                ('fecha_ultima_venta', models.DateField(blank=True, null=True)),
                ('stock_inicial', models.IntegerField(default=100)),
                ('ubicacion_almacen', models.CharField(blank=True, max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmuseo.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('museo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appmuseo.museo')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tiendas',
            field=models.ManyToManyField(through='appmuseo.Inventario', to='appmuseo.tienda'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmuseo.tienda'),
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('edad', models.IntegerField(null=True)),
                ('fecha_visita', models.DateField()),
                ('museo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmuseo.museo')),
            ],
        ),
        migrations.CreateModel(
            name='VisitaGuiada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.DurationField()),
                ('nombre_guia', models.CharField(max_length=100)),
                ('capacidad_maxima', models.IntegerField(default=20)),
                ('idioma', models.CharField(choices=[('espanol', 'Español'), ('ingles', 'Inglés')], max_length=50)),
                ('guias', models.ManyToManyField(to='appmuseo.guia')),
                ('visitantes', models.ManyToManyField(to='appmuseo.visitante')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo', models.CharField(choices=[('adulto', 'Adulto'), ('nino', 'Niño')], max_length=50)),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('visitante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appmuseo.visitante')),
            ],
        ),
    ]
