# Generated by Django 5.1.5 on 2025-01-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmuseo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='fecha_visita',
            field=models.DateField(blank=True, null=True),
        ),
    ]
