# Generated by Django 5.1.4 on 2025-02-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmuseo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
