# Generated by Django 4.2.16 on 2024-11-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmuseo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museo',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre del museo'),
        ),
    ]
