# Generated by Django 4.2.16 on 2024-12-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmuseo', '0002_alter_museo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposicion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
