# Generated by Django 5.1.4 on 2024-12-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmuseo', '0003_alter_exposicion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposicion',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='museo',
            name='ubicacion',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
