# Generated by Django 4.2.16 on 2024-12-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmuseo', '0004_alter_exposicion_descripcion_alter_museo_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='autor',
        ),
    ]
