# Generated by Django 5.1.4 on 2024-12-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmuseo', '0005_remove_obra_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='idiomas',
            field=models.CharField(choices=[('espanol', 'Español'), ('ingles', 'Inglés')], max_length=100),
        ),
        migrations.AlterField(
            model_name='obra',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_obras'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='idioma',
            field=models.CharField(choices=[('espanol', 'Español'), ('ingles', 'Inglés')], max_length=100),
        ),
    ]
